### ISSUE TITLE
Indexer should return a response when a did is not found

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/ocean-node#150]
Currently, we have: 
```
  async retrieve(id: string) {
    try {
      return await this.provider
        .collections(this.schemas[0].name)
        .documents()
        .retrieve(id)
    } catch (error) {
      return null
    }
  }

``` 

I suggest we return the error. If the market calls the indexer and nothing is found it should be able to display an error message to the user. So we can change it to:

```
  async retrieve(id: string) {
    try {
      return await this.provider
        .collections(this.schemas[0].name)
        .documents()
        .retrieve(id)
    } catch (error) {
      return error
    }
  }

```
There will also need to be some additional changes needed to make sure that this doesn't break the existing functionality. 

Then we can test it with something like this:

```
const response = await database.ddo.retrieve(fakeDid)
assert(response.status == 404)
assert(response.message == "Not found")
```

**Comment by mariacarmina** [comment]
This issue requires more workaround/refactoring because it needs update on all databases methods (nonce and ddo) and this should be reflected in the core functionality, meaning all the handlers that are depending on the DB need to be surrounded by try-catch blocks as well in order to not break what we currently have. So, IMO, this should be done after the POC.
