### ISSUE TITLE
Integration tests don't reliably work when running locally

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/ocean-node#280]
Integration tests don't reliably work when running locally, most of the time they fail even though they work fine on the CI. We need to figure out what's causing the issue and find a fix.

**Comment by paulo-ocean** [comment]
oh yeah, agree. We need to see what's going on..

**Comment by alexcos20** [comment]
make sure that all tests are using setupEnvironment at the beginning and tearDownEnvironment at the end

**Comment by paulo-ocean** [comment]
adding a bit more context here:
- we need to make sure that the .env vars / values  on `src/test/.env.test` are the same we have on  we have on `workflows/ci.yml`
- some specific tests still need to call `setupEnvironment` and `tearDownEnvironment` with their own overrides, because we might want to test a function with that specific env var set, with the env var missing and/or using defaults. But the starting point must be the same

@jamiehewitt15 , regarding the PR about integration tests, that one was about removing delays, handle test timeouts and rewrite `waitToIndex` to also use events, nothing to do with running tests locally or CI... 
The difference in those 'runs' is mostly because they have different .env settings

**Comment by bogdanfazakas** [comment]
closed by #344
